--PHASE 1 — Understand the raw data
--dataset 1 @customers
--ROW COUNT
SELECT COUNT(*) AS ROW_COUNT --99441
FROM CUSTOMERS

--COLUMN COUNT
SELECT COUNT(*) AS COLUMN_COUNT  --5
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'customers'

--COLUMN NAMES AND DATA TYPES
SELECT
COLUMN_NAME, DATA_TYPE 
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'CUSTOMERS'

--CHECKING DATA
SELECT TOP 10* 
FROM CUSTOMERS

--CHECKING CUSTOMER ID IS UNIQUE OR NOT
SELECT COUNT(*) AS TOTAL_ROW,
COUNT(DISTINCT(CUSTOMER_ID)) AS UNIQUE_CUSTOMER_ID 
FROM CUSTOMERS

--CHECKING IS NULLS IN CUSTOMER_ID
SELECT COUNT(*) AS NULL_CUST_IDS
FROM CUSTOMERS
WHERE CUSTOMER_ID IS NULL





--dataset 2 orders
-- row count 
SELECT COUNT(*) AS ROW_COUNT --99441
FROM orders

--column count
SELECT COUNT(*) AS COLUMN_COUNT  --8
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ORDERS'

--column names and data types
SELECT 
COLUMN_NAME,
DATA_TYPE 
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ORDERS'

--CHECKING DUPLICATES
SELECT COUNT(ORDER_ID) AS ORDER_ROWS,
COUNT(DISTINCT ORDER_ID) AS ORDER_ID_COUNT
FROM ORDERS 

--checking nulls in order id
SELECT COUNT(ORDER_ID) AS NULL_ORDER_IDS
FROM ORDERS
WHERE ORDER_ID IS NULL

--RETRIVING 10RECORDS
SELECT TOP 10* FROM ORDERS

--GRAIN : 1 ROW = ORDER DETAILS 






--DATASET 3 ORDERITEMS
 --ROW COUNT
SELECT COUNT(*)AS ROW_COUNT --112650
FROM ORDERITEMS

-- COLUMN COUNT
SELECT COUNT(*) AS COLUMN_COUNT --7
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'ORDERITEMS'

--COLUMN_NAMES AND DATA TYPES
SELECT 
COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'ORDERITEMS'


--unique values
select 
COUNT(DISTINCT order_id) AS UNIQUE_ORDER_ID,
count(*) as number_of_rows
from orderitems

--null
SELECT
count(order_id) as null_order_values
from orderitems
where order_id is null

--orders that contain multiple items
SELECT
order_id,
COUNT(*) AS ITEM_COUNT,
count(order_id) as total_rows
FROM orderitems
GROUP BY ORDER_ID
HAVING COUNT(*) > 1

SELECT
    COUNT(*) AS total_orderitem_rows,
    COUNT(DISTINCT order_id) AS total_unique_orders,
    COUNT(DISTINCT CASE
        WHEN item_count > 1 THEN order_id
    END) AS orders_with_multiple_items,
    COUNT(DISTINCT CASE
        WHEN item_count = 1 THEN order_id
    END) AS orders_with_one_item
FROM (
    SELECT
        order_id,
        COUNT(*) AS item_count
    FROM orderitems
    GROUP BY order_id
) AS order_summary;

select * from orderitems

--GRAIN = one row contain one item per order 
--candidate composite key: (order_id+order_item_id)
--fk: order_id 




--dataset 4 @ products

--ROW COUNT 
SELECT 
COUNT(*) AS ROW_COUNT FROM PRODUCTS --32951

--COULUMN COUNT
SELECT 
COUNT(*) AS COLUMN_COUNT FROM INFORMATION_SCHEMA.COLUMNS    --9
WHERE TABLE_NAME = 'PRODUCTS' 

--COLUMN_NAME AND DATATYPES
SELECT 
COLUMN_NAME, DATA_TYPE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'PRODUCTS'

--ASSESING TOP 10 ROWS
SELECT TOP 10* FROM PRODUCTS

--DUPLICATES
SELECT COUNT(*) AS UNIQUE_PRODUCT_ID
FROM(
SELECT DISTINCT (PRODUCT_ID) FROM PRODUCTS) AS UNIQUE_PRODUCTS

--NULLS 
SELECT COUNT(*) AS NULL_PRODUCT_IDS
FROM PRODUCTS 
WHERE PRODUCT_ID IS NULL

--GRAIN: one row represent one product with unique product id 
--candidate pk : product_id
--RELATIONSHIP: orderitems.product_id -> products.product_id 


